### ISSUE TITLE
Infinite Accounts

### ISSUE THREAD

**Issue by xdev31** [teendevops/teendevops-web#11]
Hello,
I'm a web dev, I really like your project but I noticied one thing: you can create infinite accounts with temporary emails (https://dropmail.me/)

in the register form, why don't you put a Captcha?
Thanks in advance
Greetings

**Comment by Arinerron** [comment]
Disposable email addresses disallowed in commit https://github.com/teendevops/teendevops-web/commit/302516d2f80f190a9e4152879bc896e660031459 . Thanks. Captcha will be implemented soon.

**Comment by beardog108** [comment]
It isn't as simple as this though, for example the email provider i use, cock.li, doesn't require cell verification and is therefore effectively disposable. I and many people use this service as a non-disposable email though. This is a bug that can never really be fixed 100%.
